name: Run Pytests Manually

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytests and generate JUnit report
      run: |
        pytest Test/ --junitxml=pytest-report.xml

    - name: Upload test results (optional)
      uses: actions/upload-artifact@v4
      with:
        name: pytest-report
        path: pytest-report.xml

    - name: Display test results in GitHub UI
      uses: dorny/test-reporter@v1
      if: always()  # Ensures it runs even if tests fail
      with:
        name: Pytest Results
        path: pytest-report.xml
        reporter: java-junit